import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.college.deleteMany();

  const colleges = [
    {
      name: "IIT Bombay",
      slug: "iit-bombay",
      city: "Mumbai",
      location: "Mumbai",
      state: "Maharashtra",
      fees: 220000,
      rating: 4.9,
      placementPct: 98,
      coursesOffered: ["B.Tech", "M.Tech", "PhD", "MBA"],
      type: "Government",
      description: "Premier engineering institute ranked among top 10 globally. Known for cutting-edge research and exceptional industry placements. Home to some of India's most celebrated alumni.",
      imageUrl: "https://picsum.photos/seed/iitbombay/400/200",
      cutoffRank: 100,
      examName: "JEE",
    },
    {
      name: "IIT Delhi",
      slug: "iit-delhi",
      city: "New Delhi",
      location: "New Delhi",
      state: "Delhi",
      fees: 215000,
      rating: 4.9,
      placementPct: 97,
      coursesOffered: ["B.Tech", "M.Tech", "PhD", "MBA"],
      type: "Government",
      description: "Located in the heart of the capital, IIT Delhi is a hub of innovation and research. It has produced numerous entrepreneurs, scientists, and global leaders.",
      imageUrl: "https://picsum.photos/seed/iitdelhi/400/200",
      cutoffRank: 120,
      examName: "JEE",
    },
    {
      name: "IIT Madras",
      slug: "iit-madras",
      city: "Chennai",
      location: "Chennai",
      state: "Tamil Nadu",
      fees: 210000,
      rating: 4.8,
      placementPct: 96,
      coursesOffered: ["B.Tech", "M.Tech", "PhD"],
      type: "Government",
      description: "Consistently ranked #1 in India, IIT Madras is known for its research output and strong alumni network. Set in a lush campus in Chennai.",
      imageUrl: "https://picsum.photos/seed/iitmadras/400/200",
      cutoffRank: 110,
      examName: "JEE",
    },
    {
      name: "IIT Kanpur",
      slug: "iit-kanpur",
      city: "Kanpur",
      location: "Kanpur",
      state: "UP",
      fees: 205000,
      rating: 4.8,
      placementPct: 95,
      coursesOffered: ["B.Tech", "M.Tech", "PhD"],
      type: "Government",
      description: "Known for its rigorous academics and pioneering research programs. IIT Kanpur has been the birthplace of many technological innovations in India.",
      imageUrl: "https://picsum.photos/seed/iitkanpur/400/200",
      cutoffRank: 130,
      examName: "JEE",
    },
    {
      name: "IIT Kharagpur",
      slug: "iit-kharagpur",
      city: "Kharagpur",
      location: "Kharagpur",
      state: "West Bengal",
      fees: 200000,
      rating: 4.7,
      placementPct: 94,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "PhD"],
      type: "Government",
      description: "The oldest IIT, established in 1951. Known for its diverse programs and a 2100-acre campus. Strong in engineering, law, and management education.",
      imageUrl: "https://picsum.photos/seed/iitkharagpur/400/200",
      cutoffRank: 150,
      examName: "JEE",
    },
    {
      name: "NIT Trichy",
      slug: "nit-trichy",
      city: "Tiruchirappalli",
      location: "Tiruchirappalli",
      state: "Tamil Nadu",
      fees: 150000,
      rating: 4.5,
      placementPct: 90,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "One of the top NITs in India, NIT Trichy is renowned for its strong technical education and impressive placement record. Highly sought after by engineering aspirants.",
      imageUrl: "https://picsum.photos/seed/nittrichy/400/200",
      cutoffRank: 8000,
      examName: "JEE",
    },
    {
      name: "NIT Surathkal",
      slug: "nit-surathkal",
      city: "Mangalore",
      location: "Mangalore",
      state: "Karnataka",
      fees: 145000,
      rating: 4.4,
      placementPct: 88,
      coursesOffered: ["B.Tech", "M.Tech"],
      type: "Government",
      description: "Located on the scenic Karnataka coast, NIT Surathkal offers world-class engineering education. Known for strong alumni presence in top tech companies globally.",
      imageUrl: "https://picsum.photos/seed/nitsurathkal/400/200",
      cutoffRank: 12000,
      examName: "JEE",
    },
    {
      name: "NIT Warangal",
      slug: "nit-warangal",
      city: "Warangal",
      location: "Warangal",
      state: "Telangana",
      fees: 142000,
      rating: 4.4,
      placementPct: 87,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "One of the oldest NITs with a strong tradition of academic excellence. NIT Warangal has produced leaders across industries from technology to public service.",
      imageUrl: "https://picsum.photos/seed/nitwarangal/400/200",
      cutoffRank: 14000,
      examName: "JEE",
    },
    {
      name: "BITS Pilani",
      slug: "bits-pilani",
      city: "Pilani",
      location: "Pilani",
      state: "Rajasthan",
      fees: 520000,
      rating: 4.7,
      placementPct: 93,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Pharm"],
      type: "Private",
      description: "A deemed university of eminence, BITS Pilani is known for its industry-integrated practice school program. Highly competitive admissions via BITSAT.",
      imageUrl: "https://picsum.photos/seed/bitspilani/400/200",
      cutoffRank: null,
      examName: "BITSAT",
    },
    {
      name: "VIT Vellore",
      slug: "vit-vellore",
      city: "Vellore",
      location: "Vellore",
      state: "Tamil Nadu",
      fees: 370000,
      rating: 4.2,
      placementPct: 82,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
      type: "Private",
      description: "One of India's largest private engineering universities, VIT is known for its modern infrastructure and diverse student community from across 50+ countries.",
      imageUrl: "https://picsum.photos/seed/vitvellore/400/200",
      cutoffRank: null,
      examName: "VITEEE",
    },
    {
      name: "Manipal Institute of Technology",
      slug: "manipal-institute-of-technology",
      city: "Manipal",
      location: "Manipal",
      state: "Karnataka",
      fees: 430000,
      rating: 4.1,
      placementPct: 80,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Arch"],
      type: "Private",
      description: "MIT Manipal is a premier private engineering college known for its state-of-the-art facilities and strong industry connections. Part of the Manipal University system.",
      imageUrl: "https://picsum.photos/seed/mitmanipal/400/200",
      cutoffRank: null,
      examName: "MET",
    },
    {
      name: "SRM Institute of Science and Technology",
      slug: "srm-institute-of-science-and-technology",
      city: "Chennai",
      location: "Kattankulathur",
      state: "Tamil Nadu",
      fees: 350000,
      rating: 4.0,
      placementPct: 79,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
      type: "Private",
      description: "SRM is a leading private university with strong industry partnerships. Known for its research culture and international collaborations with top global universities.",
      imageUrl: "https://picsum.photos/seed/srm/400/200",
      cutoffRank: null,
      examName: "SRMJEEE",
    },
    {
      name: "Delhi Technological University",
      slug: "delhi-technological-university",
      city: "New Delhi",
      location: "New Delhi",
      state: "Delhi",
      fees: 160000,
      rating: 4.3,
      placementPct: 85,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "Formerly Delhi College of Engineering, DTU is one of Delhi's premier engineering colleges. Known for strong placements and an active technical culture.",
      imageUrl: "https://picsum.photos/seed/dtu/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "Netaji Subhas University of Technology",
      slug: "netaji-subhas-university-of-technology",
      city: "New Delhi",
      location: "New Delhi",
      state: "Delhi",
      fees: 155000,
      rating: 4.2,
      placementPct: 83,
      coursesOffered: ["B.Tech", "M.Tech"],
      type: "Government",
      description: "NSUT (formerly NSIT) is a top Delhi government engineering college. Located in Dwarka, it offers quality technical education with strong industry linkages.",
      imageUrl: "https://picsum.photos/seed/nsut/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "IIM Ahmedabad",
      slug: "iim-ahmedabad",
      city: "Ahmedabad",
      location: "Ahmedabad",
      state: "Gujarat",
      fees: 2400000,
      rating: 4.9,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "India's most prestigious management institution. IIM Ahmedabad consistently ranks #1 for MBA in Asia. Average placement package exceeds ₹35 LPA.",
      imageUrl: "https://picsum.photos/seed/iima/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "IIM Bangalore",
      slug: "iim-bangalore",
      city: "Bangalore",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 2300000,
      rating: 4.9,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "Located in India's Silicon Valley, IIM Bangalore has strong ties with the tech industry. Known for entrepreneurship and innovation-driven curriculum.",
      imageUrl: "https://picsum.photos/seed/iimb/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "IIM Calcutta",
      slug: "iim-calcutta",
      city: "Kolkata",
      location: "Kolkata",
      state: "West Bengal",
      fees: 2250000,
      rating: 4.8,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "Asia's first management institution, IIM Calcutta is known for its finance specialization and consulting culture. Part of the elite IIM ABC trio.",
      imageUrl: "https://picsum.photos/seed/iimc/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "Amity University",
      slug: "amity-university",
      city: "Noida",
      location: "Noida",
      state: "UP",
      fees: 280000,
      rating: 3.8,
      placementPct: 75,
      coursesOffered: ["B.Tech", "BCA", "MBA", "B.Com", "B.Sc"],
      type: "Private",
      description: "One of India's largest private universities with campuses across India and abroad. Known for diverse programs and strong corporate recruiter relationships.",
      imageUrl: "https://picsum.photos/seed/amity/400/200",
      cutoffRank: null,
      examName: "AMITYJEE",
    },
    {
      name: "Symbiosis Institute of Technology",
      slug: "symbiosis-institute-of-technology",
      city: "Pune",
      location: "Pune",
      state: "Maharashtra",
      fees: 400000,
      rating: 4.0,
      placementPct: 81,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Private",
      description: "Part of the Symbiosis International University, SIT Pune is known for holistic education. Strong focus on industry readiness and entrepreneurship.",
      imageUrl: "https://picsum.photos/seed/sit/400/200",
      cutoffRank: null,
      examName: "SET",
    },
    {
      name: "Christ University",
      slug: "christ-university",
      city: "Bangalore",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 200000,
      rating: 4.1,
      placementPct: 78,
      coursesOffered: ["B.Tech", "BCA", "MBA", "B.Com", "B.Sc"],
      type: "Private",
      description: "A deemed university known for academic rigor and value-based education. Christ University offers diverse programs across engineering, science, and commerce.",
      imageUrl: "https://picsum.photos/seed/christ/400/200",
      cutoffRank: null,
      examName: "CUET",
    },
    {
      name: "PSG College of Technology",
      slug: "psg-college-of-technology",
      city: "Coimbatore",
      location: "Coimbatore",
      state: "Tamil Nadu",
      fees: 120000,
      rating: 4.3,
      placementPct: 86,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA"],
      type: "Private",
      description: "PSG Tech is a top-ranked autonomous institution in Tamil Nadu. Known for strong industry connections, especially with the textile and manufacturing sectors.",
      imageUrl: "https://picsum.photos/seed/psgtech/400/200",
      cutoffRank: null,
      examName: "TNEA",
    },
    {
      name: "Thapar Institute of Engineering and Technology",
      slug: "thapar-institute-of-engineering-and-technology",
      city: "Patiala",
      location: "Patiala",
      state: "Punjab",
      fees: 450000,
      rating: 4.2,
      placementPct: 84,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Private",
      description: "A deemed university in Punjab, Thapar is known for its strong B.Tech programs and good placement track record. Collaborations with many international universities.",
      imageUrl: "https://picsum.photos/seed/thapar/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "Jadavpur University",
      slug: "jadavpur-university",
      city: "Kolkata",
      location: "Kolkata",
      state: "West Bengal",
      fees: 50000,
      rating: 4.4,
      placementPct: 85,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Sc", "PhD"],
      type: "Government",
      description: "One of the most prestigious state universities in India. Jadavpur University is particularly known for its engineering and arts faculties with strong research output.",
      imageUrl: "https://picsum.photos/seed/jadavpur/400/200",
      cutoffRank: null,
      examName: "WBJEE",
    },
    {
      name: "Coimbatore Institute of Technology",
      slug: "coimbatore-institute-of-technology",
      city: "Coimbatore",
      location: "Coimbatore",
      state: "Tamil Nadu",
      fees: 95000,
      rating: 4.0,
      placementPct: 77,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "CIT Coimbatore is a government-aided autonomous institution known for affordable quality education. Strong industry connections in the Coimbatore industrial belt.",
      imageUrl: "https://picsum.photos/seed/citcoimbatore/400/200",
      cutoffRank: null,
      examName: "TNEA",
    },
    {
      name: "Birla Institute of Technology Mesra",
      slug: "birla-institute-of-technology-mesra",
      city: "Ranchi",
      location: "Ranchi",
      state: "Jharkhand",
      fees: 300000,
      rating: 3.9,
      placementPct: 76,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA", "B.Pharm"],
      type: "Private",
      description: "BIT Mesra is a deemed university known for quality engineering education and diverse programs. Located in the scenic Mesra campus near Ranchi, Jharkhand.",
      imageUrl: "https://picsum.photos/seed/bitmesra/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
  ];

  for (const college of colleges) {
    await (prisma.college as any).create({ data: college });
  }

  console.log(`Seeded ${colleges.length} colleges successfully.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

const newColleges = [
  {
    name: "Anna University",
    slug: "anna-university",
    city: "Chennai",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    fees: 50000,
    rating: 4.2,
    placementPct: 85,
    coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA"],
    description: "One of the top technical universities in South India with excellent research facilities.",
    imageUrl: "https://picsum.photos/seed/annauniversity/400/200",
    cutoffRank: 5000,
    examName: "TNEA",
  },
  {
    name: "Pune Institute of Computer Technology",
    slug: "pune-institute-of-computer-technology",
    city: "Pune",
    location: "Pune",
    state: "Maharashtra",
    type: "Private",
    fees: 180000,
    rating: 4.1,
    placementPct: 88,
    coursesOffered: ["B.Tech", "M.Tech"],
    description: "Premier computer technology institute in Pune with strong industry connections.",
    imageUrl: "https://picsum.photos/seed/pict/400/200",
    cutoffRank: 8000,
    examName: "MHT-CET",
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    slug: "kalinga-institute-of-industrial-technology",
    city: "Bhubaneswar",
    location: "Bhubaneswar",
    state: "Odisha",
    type: "Private",
    fees: 350000,
    rating: 4.0,
    placementPct: 82,
    coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    description: "KIIT is a deemed university known for excellent placements and campus life.",
    imageUrl: "https://picsum.photos/seed/kiit/400/200",
    cutoffRank: 15000,
    examName: "JEE",
  },
  {
    name: "SRM University Chennai",
    slug: "srm-university-chennai",
    city: "Chennai",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    fees: 250000,
    rating: 4.0,
    placementPct: 80,
    coursesOffered: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
    description: "One of India's top private universities with strong global partnerships.",
    imageUrl: "https://picsum.photos/seed/srmchennai/400/200",
    cutoffRank: 20000,
    examName: "SRMJEEE",
  },
  {
    name: "Vellore Institute of Technology Chennai",
    slug: "vit-chennai",
    city: "Chennai",
    location: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    fees: 230000,
    rating: 4.1,
    placementPct: 84,
    coursesOffered: ["B.Tech", "M.Tech", "MBA"],
    description: "VIT Chennai campus offering world-class education and research opportunities.",
    imageUrl: "https://picsum.photos/seed/vitchennai/400/200",
    cutoffRank: 18000,
    examName: "VITEEE",
  },
  {
    name: "Lovely Professional University",
    slug: "lovely-professional-university",
    city: "Phagwara",
    location: "Phagwara",
    state: "Punjab",
    type: "Private",
    fees: 180000,
    rating: 3.9,
    placementPct: 78,
    coursesOffered: ["B.Tech", "MBA", "BCA", "MCA", "BBA"],
    description: "India's largest private university offering diverse programs with strong placement support.",
    imageUrl: "https://picsum.photos/seed/lpu/400/200",
    cutoffRank: 50000,
    examName: "LPUNEST",
  },
  {
    name: "Chandigarh University",
    slug: "chandigarh-university",
    city: "Chandigarh",
    location: "Chandigarh",
    state: "Punjab",
    type: "Private",
    fees: 200000,
    rating: 4.0,
    placementPct: 83,
    coursesOffered: ["B.Tech", "MBA", "BCA", "MCA", "BBA"],
    description: "One of the fastest growing universities in India with excellent industry tie-ups.",
    imageUrl: "https://picsum.photos/seed/cu/400/200",
    cutoffRank: 40000,
    examName: "CUCET",
  },
  {
    name: "Institute of Chemical Technology",
    slug: "institute-of-chemical-technology",
    city: "Mumbai",
    location: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    fees: 80000,
    rating: 4.4,
    placementPct: 92,
    coursesOffered: ["B.Tech", "M.Tech", "PhD"],
    description: "India's top chemical technology institute with outstanding research and placements.",
    imageUrl: "https://picsum.photos/seed/ict/400/200",
    cutoffRank: 3000,
    examName: "JEE",
  },
  {
    name: "NALSAR University of Law",
    slug: "nalsar-university-of-law",
    city: "Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    type: "Government",
    fees: 120000,
    rating: 4.5,
    placementPct: 90,
    coursesOffered: ["LLB", "LLM", "PhD"],
    description: "One of India's premier law universities with excellent faculty and moot court tradition.",
    imageUrl: "https://picsum.photos/seed/nalsar/400/200",
    cutoffRank: 500,
    examName: "CLAT",
  },
  {
    name: "National Law School of India University",
    slug: "national-law-school-of-india-university",
    city: "Bangalore",
    location: "Bangalore",
    state: "Karnataka",
    type: "Government",
    fees: 130000,
    rating: 4.7,
    placementPct: 95,
    coursesOffered: ["LLB", "LLM", "PhD"],
    description: "India's top ranked law school producing exceptional legal professionals.",
    imageUrl: "https://picsum.photos/seed/nlsiu/400/200",
    cutoffRank: 100,
    examName: "CLAT",
  },
  {
    name: "IIT Roorkee",
    slug: "iit-roorkee",
    city: "Roorkee",
    location: "Roorkee",
    state: "Uttarakhand",
    type: "Government",
    fees: 220000,
    rating: 4.7,
    placementPct: 95,
    coursesOffered: ["B.Tech", "M.Tech", "MBA", "PhD"],
    description: "India's oldest technical institute with world-class research and placement record.",
    imageUrl: "https://picsum.photos/seed/iitroorkee/400/200",
    cutoffRank: 3000,
    examName: "JEE",
  },
  {
    name: "IIT Guwahati",
    slug: "iit-guwahati",
    city: "Guwahati",
    location: "Guwahati",
    state: "Assam",
    type: "Government",
    fees: 220000,
    rating: 4.6,
    placementPct: 93,
    coursesOffered: ["B.Tech", "M.Tech", "PhD"],
    description: "Premier IIT in Northeast India with strong research programs and industry connections.",
    imageUrl: "https://picsum.photos/seed/iitguwahati/400/200",
    cutoffRank: 5000,
    examName: "JEE",
  },
  {
    name: "IIT Hyderabad",
    slug: "iit-hyderabad",
    city: "Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    type: "Government",
    fees: 220000,
    rating: 4.5,
    placementPct: 92,
    coursesOffered: ["B.Tech", "M.Tech", "PhD"],
    description: "Young and dynamic IIT known for innovation and strong startup culture.",
    imageUrl: "https://picsum.photos/seed/iithyd/400/200",
    cutoffRank: 6000,
    examName: "JEE",
  },
  {
    name: "XLRI Jamshedpur",
    slug: "xlri-jamshedpur",
    city: "Jamshedpur",
    location: "Jamshedpur",
    state: "Jharkhand",
    type: "Private",
    fees: 1200000,
    rating: 4.6,
    placementPct: 100,
    coursesOffered: ["MBA", "PGDM", "PhD"],
    description: "India's top HR and business management institute with 100% placement record.",
    imageUrl: "https://picsum.photos/seed/xlri/400/200",
    cutoffRank: 99,
    examName: "XAT",
  },
  {
    name: "SP Jain Institute of Management",
    slug: "sp-jain-institute-of-management",
    city: "Mumbai",
    location: "Mumbai",
    state: "Maharashtra",
    type: "Private",
    fees: 1100000,
    rating: 4.4,
    placementPct: 98,
    coursesOffered: ["MBA", "PGDM"],
    description: "Top B-school in Mumbai with excellent industry connections and global exposure.",
    imageUrl: "https://picsum.photos/seed/spjain/400/200",
    cutoffRank: 98,
    examName: "CAT",
  },
  {
    name: "Osmania University",
    slug: "osmania-university",
    city: "Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    type: "Government",
    fees: 40000,
    rating: 3.8,
    placementPct: 72,
    coursesOffered: ["B.Tech", "MBA", "MCA", "LLB", "PhD"],
    description: "One of the oldest and largest universities in India with diverse academic programs.",
    imageUrl: "https://picsum.photos/seed/osmania/400/200",
    cutoffRank: 30000,
    examName: "TS EAMCET",
  },
  {
    name: "Banaras Hindu University",
    slug: "banaras-hindu-university",
    city: "Varanasi",
    location: "Varanasi",
    state: "Uttar Pradesh",
    type: "Government",
    fees: 30000,
    rating: 4.2,
    placementPct: 80,
    coursesOffered: ["B.Tech", "MBA", "LLB", "MBBS", "PhD"],
    description: "One of Asia's largest residential universities with rich heritage and strong academics.",
    imageUrl: "https://picsum.photos/seed/bhu/400/200",
    cutoffRank: 10000,
    examName: "JEE",
  },
  {
    name: "Aligarh Muslim University",
    slug: "aligarh-muslim-university",
    city: "Aligarh",
    location: "Aligarh",
    state: "Uttar Pradesh",
    type: "Government",
    fees: 35000,
    rating: 4.0,
    placementPct: 75,
    coursesOffered: ["B.Tech", "MBBS", "LLB", "MBA", "PhD"],
    description: "Historic central university known for quality education and diverse student community.",
    imageUrl: "https://picsum.photos/seed/amu/400/200",
    cutoffRank: 25000,
    examName: "AMUEEE",
  },
  {
    name: "Savitribai Phule Pune University",
    slug: "savitribai-phule-pune-university",
    city: "Pune",
    location: "Pune",
    state: "Maharashtra",
    type: "Government",
    fees: 45000,
    rating: 4.0,
    placementPct: 76,
    coursesOffered: ["B.Tech", "MBA", "MCA", "LLB", "PhD"],
    description: "One of Maharashtra's premier universities with strong research and academic programs.",
    imageUrl: "https://picsum.photos/seed/sppu/400/200",
    cutoffRank: 20000,
    examName: "MHT-CET",
  },
  {
    name: "Delhi University",
    slug: "delhi-university",
    city: "New Delhi",
    location: "New Delhi",
    state: "Delhi",
    type: "Government",
    fees: 25000,
    rating: 4.3,
    placementPct: 82,
    coursesOffered: ["B.Tech", "MBA", "LLB", "MBBS", "BA", "BCom"],
    description: "India's most prestigious central university with world-class faculty and alumni network.",
    imageUrl: "https://picsum.photos/seed/du/400/200",
    cutoffRank: 500,
    examName: "CUET",
  },
];

for (const college of newColleges) {
  await (prisma.college as any).create({ data: college });
}
console.log("Seeded 20 more colleges successfully.");

// Bennett University
await (prisma.college as any).create({
  data: {
    name: "Bennett University",
    slug: "bennett-university",
    city: "Greater Noida",
    location: "Greater Noida",
    state: "Uttar Pradesh",
    country: "India",
    type: "Private",
    fees: 350000,
    rating: 4.1,
    placementPct: 82,
    coursesOffered: ["B.Tech", "MBA", "BCA", "MCA", "B.Sc"],
    description: "Bennett University is a Times Group institution offering world-class education with strong industry connections and modern campus facilities in Greater Noida.",
    imageUrl: "https://picsum.photos/seed/bennett/400/200",
    cutoffRank: 50000,
    examName: "JEE",
    reviewCount: 0,
    hostelAvailable: true,
    established: 2016,
    naac: "A",
    websiteUrl: "https://www.bennett.edu.in",
  }
});
console.log("Added Bennett University successfully.");
