import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.college.deleteMany();

  const colleges = [
    {
      name: "IIT Bombay",
      location: "Mumbai",
      state: "Maharashtra",
      fees: 220000,
      rating: 4.9,
      placementPct: 98,
      coursesOffered: ["B.Tech", "M.Tech", "PhD", "MBA"],
      type: "Government",
      description: "Premier engineering institute ranked among top 10 globally. Known for cutting-edge research and exceptional industry placements. Home to some of India's most celebrated alumni.",
      imageUrl: "https://picsum.photos/seed/iitbombay/400/200",
      cutoffRank: 100,
      examName: "JEE",
    },
    {
      name: "IIT Delhi",
      location: "New Delhi",
      state: "Delhi",
      fees: 215000,
      rating: 4.9,
      placementPct: 97,
      coursesOffered: ["B.Tech", "M.Tech", "PhD", "MBA"],
      type: "Government",
      description: "Located in the heart of the capital, IIT Delhi is a hub of innovation and research. It has produced numerous entrepreneurs, scientists, and global leaders.",
      imageUrl: "https://picsum.photos/seed/iitdelhi/400/200",
      cutoffRank: 120,
      examName: "JEE",
    },
    {
      name: "IIT Madras",
      location: "Chennai",
      state: "Tamil Nadu",
      fees: 210000,
      rating: 4.8,
      placementPct: 96,
      coursesOffered: ["B.Tech", "M.Tech", "PhD"],
      type: "Government",
      description: "Consistently ranked #1 in India, IIT Madras is known for its research output and strong alumni network. Set in a lush campus in Chennai.",
      imageUrl: "https://picsum.photos/seed/iitmadras/400/200",
      cutoffRank: 110,
      examName: "JEE",
    },
    {
      name: "IIT Kanpur",
      location: "Kanpur",
      state: "UP",
      fees: 205000,
      rating: 4.8,
      placementPct: 95,
      coursesOffered: ["B.Tech", "M.Tech", "PhD"],
      type: "Government",
      description: "Known for its rigorous academics and pioneering research programs. IIT Kanpur has been the birthplace of many technological innovations in India.",
      imageUrl: "https://picsum.photos/seed/iitkanpur/400/200",
      cutoffRank: 130,
      examName: "JEE",
    },
    {
      name: "IIT Kharagpur",
      location: "Kharagpur",
      state: "West Bengal",
      fees: 200000,
      rating: 4.7,
      placementPct: 94,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "PhD"],
      type: "Government",
      description: "The oldest IIT, established in 1951. Known for its diverse programs and a 2100-acre campus. Strong in engineering, law, and management education.",
      imageUrl: "https://picsum.photos/seed/iitkharagpur/400/200",
      cutoffRank: 150,
      examName: "JEE",
    },
    {
      name: "NIT Trichy",
      location: "Tiruchirappalli",
      state: "Tamil Nadu",
      fees: 150000,
      rating: 4.5,
      placementPct: 90,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "One of the top NITs in India, NIT Trichy is renowned for its strong technical education and impressive placement record. Highly sought after by engineering aspirants.",
      imageUrl: "https://picsum.photos/seed/nittrichy/400/200",
      cutoffRank: 8000,
      examName: "JEE",
    },
    {
      name: "NIT Surathkal",
      location: "Mangalore",
      state: "Karnataka",
      fees: 145000,
      rating: 4.4,
      placementPct: 88,
      coursesOffered: ["B.Tech", "M.Tech"],
      type: "Government",
      description: "Located on the scenic Karnataka coast, NIT Surathkal offers world-class engineering education. Known for strong alumni presence in top tech companies globally.",
      imageUrl: "https://picsum.photos/seed/nitsurathkal/400/200",
      cutoffRank: 12000,
      examName: "JEE",
    },
    {
      name: "NIT Warangal",
      location: "Warangal",
      state: "Telangana",
      fees: 142000,
      rating: 4.4,
      placementPct: 87,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "One of the oldest NITs with a strong tradition of academic excellence. NIT Warangal has produced leaders across industries from technology to public service.",
      imageUrl: "https://picsum.photos/seed/nitwarangal/400/200",
      cutoffRank: 14000,
      examName: "JEE",
    },
    {
      name: "BITS Pilani",
      location: "Pilani",
      state: "Rajasthan",
      fees: 520000,
      rating: 4.7,
      placementPct: 93,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Pharm"],
      type: "Private",
      description: "A deemed university of eminence, BITS Pilani is known for its industry-integrated practice school program. Highly competitive admissions via BITSAT.",
      imageUrl: "https://picsum.photos/seed/bitspilani/400/200",
      cutoffRank: null,
      examName: "BITSAT",
    },
    {
      name: "VIT Vellore",
      location: "Vellore",
      state: "Tamil Nadu",
      fees: 370000,
      rating: 4.2,
      placementPct: 82,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
      type: "Private",
      description: "One of India's largest private engineering universities, VIT is known for its modern infrastructure and diverse student community from across 50+ countries.",
      imageUrl: "https://picsum.photos/seed/vitvellore/400/200",
      cutoffRank: null,
      examName: "VITEEE",
    },
    {
      name: "Manipal Institute of Technology",
      location: "Manipal",
      state: "Karnataka",
      fees: 430000,
      rating: 4.1,
      placementPct: 80,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Arch"],
      type: "Private",
      description: "MIT Manipal is a premier private engineering college known for its state-of-the-art facilities and strong industry connections. Part of the Manipal University system.",
      imageUrl: "https://picsum.photos/seed/mitmanipal/400/200",
      cutoffRank: null,
      examName: "MET",
    },
    {
      name: "SRM Institute of Science and Technology",
      location: "Kattankulathur",
      state: "Tamil Nadu",
      fees: 350000,
      rating: 4.0,
      placementPct: 79,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
      type: "Private",
      description: "SRM is a leading private university with strong industry partnerships. Known for its research culture and international collaborations with top global universities.",
      imageUrl: "https://picsum.photos/seed/srm/400/200",
      cutoffRank: null,
      examName: "SRMJEEE",
    },
    {
      name: "Delhi Technological University",
      location: "New Delhi",
      state: "Delhi",
      fees: 160000,
      rating: 4.3,
      placementPct: 85,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "Formerly Delhi College of Engineering, DTU is one of Delhi's premier engineering colleges. Known for strong placements and an active technical culture.",
      imageUrl: "https://picsum.photos/seed/dtu/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "Netaji Subhas University of Technology",
      location: "New Delhi",
      state: "Delhi",
      fees: 155000,
      rating: 4.2,
      placementPct: 83,
      coursesOffered: ["B.Tech", "M.Tech"],
      type: "Government",
      description: "NSUT (formerly NSIT) is a top Delhi government engineering college. Located in Dwarka, it offers quality technical education with strong industry linkages.",
      imageUrl: "https://picsum.photos/seed/nsut/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "IIM Ahmedabad",
      location: "Ahmedabad",
      state: "Gujarat",
      fees: 2400000,
      rating: 4.9,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "India's most prestigious management institution. IIM Ahmedabad consistently ranks #1 for MBA in Asia. Average placement package exceeds ₹35 LPA.",
      imageUrl: "https://picsum.photos/seed/iima/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "IIM Bangalore",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 2300000,
      rating: 4.9,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "Located in India's Silicon Valley, IIM Bangalore has strong ties with the tech industry. Known for entrepreneurship and innovation-driven curriculum.",
      imageUrl: "https://picsum.photos/seed/iimb/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "IIM Calcutta",
      location: "Kolkata",
      state: "West Bengal",
      fees: 2250000,
      rating: 4.8,
      placementPct: 100,
      coursesOffered: ["MBA", "PhD", "Executive MBA"],
      type: "Government",
      description: "Asia's first management institution, IIM Calcutta is known for its finance specialization and consulting culture. Part of the elite IIM ABC trio.",
      imageUrl: "https://picsum.photos/seed/iimc/400/200",
      cutoffRank: null,
      examName: "CAT",
    },
    {
      name: "Amity University",
      location: "Noida",
      state: "UP",
      fees: 280000,
      rating: 3.8,
      placementPct: 75,
      coursesOffered: ["B.Tech", "BCA", "MBA", "B.Com", "B.Sc"],
      type: "Private",
      description: "One of India's largest private universities with campuses across India and abroad. Known for diverse programs and strong corporate recruiter relationships.",
      imageUrl: "https://picsum.photos/seed/amity/400/200",
      cutoffRank: null,
      examName: "AMITYJEE",
    },
    {
      name: "Symbiosis Institute of Technology",
      location: "Pune",
      state: "Maharashtra",
      fees: 400000,
      rating: 4.0,
      placementPct: 81,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Private",
      description: "Part of the Symbiosis International University, SIT Pune is known for holistic education. Strong focus on industry readiness and entrepreneurship.",
      imageUrl: "https://picsum.photos/seed/sit/400/200",
      cutoffRank: null,
      examName: "SET",
    },
    {
      name: "Christ University",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 200000,
      rating: 4.1,
      placementPct: 78,
      coursesOffered: ["B.Tech", "BCA", "MBA", "B.Com", "B.Sc"],
      type: "Private",
      description: "A deemed university known for academic rigor and value-based education. Christ University offers diverse programs across engineering, science, and commerce.",
      imageUrl: "https://picsum.photos/seed/christ/400/200",
      cutoffRank: null,
      examName: "CUET",
    },
    {
      name: "PSG College of Technology",
      location: "Coimbatore",
      state: "Tamil Nadu",
      fees: 120000,
      rating: 4.3,
      placementPct: 86,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA"],
      type: "Private",
      description: "PSG Tech is a top-ranked autonomous institution in Tamil Nadu. Known for strong industry connections, especially with the textile and manufacturing sectors.",
      imageUrl: "https://picsum.photos/seed/psgtech/400/200",
      cutoffRank: null,
      examName: "TNEA",
    },
    {
      name: "Thapar Institute of Engineering and Technology",
      location: "Patiala",
      state: "Punjab",
      fees: 450000,
      rating: 4.2,
      placementPct: 84,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Private",
      description: "A deemed university in Punjab, Thapar is known for its strong B.Tech programs and good placement track record. Collaborations with many international universities.",
      imageUrl: "https://picsum.photos/seed/thapar/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
    {
      name: "Jadavpur University",
      location: "Kolkata",
      state: "West Bengal",
      fees: 50000,
      rating: 4.4,
      placementPct: 85,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "B.Sc", "PhD"],
      type: "Government",
      description: "One of the most prestigious state universities in India. Jadavpur University is particularly known for its engineering and arts faculties with strong research output.",
      imageUrl: "https://picsum.photos/seed/jadavpur/400/200",
      cutoffRank: null,
      examName: "WBJEE",
    },
    {
      name: "Coimbatore Institute of Technology",
      location: "Coimbatore",
      state: "Tamil Nadu",
      fees: 95000,
      rating: 4.0,
      placementPct: 77,
      coursesOffered: ["B.Tech", "M.Tech", "MBA"],
      type: "Government",
      description: "CIT Coimbatore is a government-aided autonomous institution known for affordable quality education. Strong industry connections in the Coimbatore industrial belt.",
      imageUrl: "https://picsum.photos/seed/citcoimbatore/400/200",
      cutoffRank: null,
      examName: "TNEA",
    },
    {
      name: "Birla Institute of Technology Mesra",
      location: "Ranchi",
      state: "Jharkhand",
      fees: 300000,
      rating: 3.9,
      placementPct: 76,
      coursesOffered: ["B.Tech", "M.Tech", "MBA", "MCA", "B.Pharm"],
      type: "Private",
      description: "BIT Mesra is a deemed university known for quality engineering education and diverse programs. Located in the scenic Mesra campus near Ranchi, Jharkhand.",
      imageUrl: "https://picsum.photos/seed/bitmesra/400/200",
      cutoffRank: null,
      examName: "JEE",
    },
  ];

  for (const college of colleges) {
    await (prisma.college as any).create({ data: college });
  }

  console.log(`Seeded ${colleges.length} colleges successfully.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
